## Data loading

In [1]:
%pip install pandas numpy matplotlib seaborn

Note: you may need to restart the kernel to use updated packages.


In [2]:
!python -m pip install --upgrade pip


In [3]:
import pandas as pd
import json

In [5]:
file_path = '/Users/victoriavu25/btt_data/prepped_business.json'

df = pd.read_json(file_path)  # Assuming each line is a separate JSON object
print(df.head())  # Display the first few rows of the DataFrame
print(df.info())  # Get information about the DataFrame (e.g., column types)
pd.set_option('display.max_columns', None)  # This will display all columns
print(df)

               business_id                name        address          city  \
3   MTSW4McQd7CbVtyjqoe9mw  St Honore Pastries    935 Race St  Philadelphia   
15  MUTTqe8uqyMdBl186RmNeA            Tuna Bar    205 Race St  Philadelphia   
19  ROeacJQwBeh05Rqg7F6TCg                 BAP  1224 South St  Philadelphia   
28  QdN72BWoyFypdGJhhI5r7g             Bar One   767 S 9th St  Philadelphia   
31  Mjboz24M9NlBeiOJKLEd_Q    DeSandro on Main   4105 Main St  Philadelphia   

   state  postal_code   latitude  longitude  stars  review_count  is_open  \
3     PA        19107  39.955505 -75.155564    4.0            80        1   
15    PA        19106  39.953949 -75.143226    4.0           245        1   
19    PA        19147  39.943223 -75.162568    4.5           205        1   
28    PA        19147  39.939825 -75.157447    4.0            65        0   
31    PA        19127  40.022466 -75.218314    3.0            41        0   

                                           categories  Restaur

In [6]:
# # Select only the desired columns
# columns_to_keep = ['stars',
#                    'business_id',
#                    'RestaurantsReservations_True',
#     'RestaurantsTakeOut_True',
#     'WiFi_encoded',
#     'BusinessAcceptsCreditCards_True',
#     'Parking_garage_True',
#     'Parking_street_True',
#      'Parking_validated_True',
#     'Caters_True',
#     'GoodForKids_True',
#     'HasTV_True',
#     'NoiseLevel',
#     'OutdoorSeating_True',
#     'RestaurantsAttire_encoded',
#     'RestaurantsDelivery_True',
#     'RestaurantsGoodForGroups_True',
#     'RestaurantsPriceRange2',
#         'Ambience_touristy_True',
#     'Ambience_hipster_True',
#     'Ambience_romantic_True',
#     'Ambience_divey_True',
#     'Ambience_intimate_True',
#     'Ambience_trendy_True',
#     'Ambience_upscale_True',
#     'Ambience_classy_True',
#     'Ambience_casual_True',
#     'BikeParking_True']
# df_filtered = df[columns_to_keep]

# # Display the resulting DataFrame
# print(df_filtered)


In [9]:
# Create a new column 'high_rating' based on the 'stars' column
df['high_rating'] = (df['stars'] >= 4).astype(int)

# Display the DataFrame with the new column
print(df)


                   business_id                           name  \
3       MTSW4McQd7CbVtyjqoe9mw             St Honore Pastries   
15      MUTTqe8uqyMdBl186RmNeA                       Tuna Bar   
19      ROeacJQwBeh05Rqg7F6TCg                            BAP   
28      QdN72BWoyFypdGJhhI5r7g                        Bar One   
31      Mjboz24M9NlBeiOJKLEd_Q               DeSandro on Main   
...                        ...                            ...   
150298  gPr1io7ks0Eo3FDsnDTYfg                      Tata Cafe   
150306  wVxXRFf10zTTAs11nr4xeA                   PrimoHoagies   
150319  8n93L-ilMAsvwUatarykSg                    Kitchen Gia   
150325  l9eLGG9ZKpLJzboZq-9LRQ                           Wawa   
150336  WnT9NIzQgLlILjPT0kEcsQ  Adelita Taqueria & Restaurant   

                    address             city state  postal_code   latitude  \
3               935 Race St     Philadelphia    PA        19107  39.955505   
15              205 Race St     Philadelphia    PA        19106

In [16]:
import scipy.stats as stats

significant_columns = []
drop_columns = []

# Iterate over the columns in the DataFrame, excluding 'stars' and 'business_id'
for column in df.columns:
    if column not in ['stars', 'high_rating', 'business_id','categories','name', 'address', 'city', 'postal_code', 'review_count', 'is_open']:  # Exclude non-relevant columns
        # Perform the Chi-Square test
        # Create a contingency table (cross-tabulation of 'stars' and the current column)
        contingency_table = pd.crosstab(df['high_rating'], df[column])

        # Apply the Chi-Square test
        chi2_stat, p_val, dof, expected = stats.chi2_contingency(contingency_table)

        # Print the results
        print(f"Chi-Square Test for {column}:")
        print(f"Chi-Square Statistic: {chi2_stat}")
        print(f"P-Value: {p_val}")
        print(f"Degrees of Freedom: {dof}")
        print(f"Expected Frequencies:\n{expected}\n")

        # Check significance level
        if p_val < 0.05:
            significant_columns.append(column)
            print(f"There is a significant association between 'high_rating' and '{column}'.\n")
        else:
            drop_columns.append(column)
            print(f"There is no significant association between 'high_rating' and '{column}'.\n")


Chi-Square Test for state:
Chi-Square Statistic: 0.0
P-Value: 1.0
Degrees of Freedom: 0
Expected Frequencies:
[[7527.]
 [5494.]]

There is no significant association between 'high_rating' and 'state'.

Chi-Square Test for latitude:
Chi-Square Statistic: 12471.828540887976
P-Value: 0.2788100560312765
Degrees of Freedom: 12380
Expected Frequencies:
[[0.5780662 0.5780662 0.5780662 ... 0.5780662 0.5780662 0.5780662]
 [0.4219338 0.4219338 0.4219338 ... 0.4219338 0.4219338 0.4219338]]

There is no significant association between 'high_rating' and 'latitude'.

Chi-Square Test for longitude:
Chi-Square Statistic: 12308.514036510282
P-Value: 0.3294821886858101
Degrees of Freedom: 12240
Expected Frequencies:
[[0.5780662 0.5780662 0.5780662 ... 0.5780662 0.5780662 0.5780662]
 [0.4219338 0.4219338 0.4219338 ... 0.4219338 0.4219338 0.4219338]]

There is no significant association between 'high_rating' and 'longitude'.

Chi-Square Test for RestaurantsPriceRange2:
Chi-Square Statistic: 8.167781298663

In [17]:
print("Significant Columns:")
print(significant_columns)
print("\nColumns to Drop:")
print(drop_columns)

Significant Columns:
['RestaurantsPriceRange2', 'NoiseLevel', 'RestaurantsDelivery_True', 'OutdoorSeating_True', 'BusinessAcceptsCreditCards_True', 'BikeParking_True', 'Caters_True', 'GoodForKids_True', 'RestaurantsGoodForGroups_True', 'HasTV_True', 'Ambience_hipster_True', 'Ambience_romantic_True', 'Ambience_intimate_True', 'Ambience_trendy_True', 'Ambience_upscale_True', 'Ambience_classy_True', 'Ambience_casual_True', 'Parking_street_True', 'Parking_lot_True', 'Parking_valet_True', 'WiFi_encoded', 'Monday_morning', 'Monday_midday', 'Monday_night', 'Tuesday_morning', 'Tuesday_midday', 'Wednesday_morning', 'Wednesday_midday', 'Wednesday_night', 'Thursday_morning', 'Thursday_midday', 'Thursday_night', 'Friday_morning', 'Friday_midday', 'Friday_night', 'Saturday_morning', 'Saturday_midday', 'Saturday_night', 'Sunday_morning', 'Sunday_midday', 'Sunday_night']

Columns to Drop:
['state', 'latitude', 'longitude', 'RestaurantsTakeOut_True', 'RestaurantsReservations_True', 'Ambience_touristy_